# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ef4ff3efb9a976613d89f40fe616d7381293c83afe277fddb38c74277b1c1dc1c87b27f6b0e03c0a995846417deb0acc1db98201b5a917a322963b0f21be82

test:
  secret_key_base: c7ac63c232647b5e3f283e75f798602089cef3465a1551aa2b19baa977c05157cced2426ad398ce23ad050f1003ef34f48c3dfe86d02f6f48b5b89790be72b0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
